### ISSUE TITLE
Add viewer link to download full SQLite database file

### ISSUE THREAD

**Issue by chosak** [cfpb/crawsqueal#11]
For now the easiest place for this link might be the page header or footer.

For the header, maybe similar to how the language links appear [on cf.gov](https://www.consumerfinance.gov/):

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/654645/172179137-044d6e1d-0c80-4ff2-a8d4-2406a16428e3.png">

For the footer, maybe in a new link section, again, like cf.gov:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/654645/172179248-ab370f07-5cd4-4294-af4f-57476000a172.png">

**Comment by chosak** [comment]
Prototype header link:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/654645/172194131-c21bb6f8-7fe3-41af-b90a-79faed56c2be.png">

Prototype footer link:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/654645/172194207-4279c33c-0457-47c3-a926-5684c5ebdf2e.png">

@csebianlander @ceceliatroyan @huetingj @sonnakim do you have a preference for either/both of these? Any other ideas or suggestions (say, to the link text) are welcome as well.

**Comment by contolini** [comment]
Maybe add a word like `entire` or `raw` to emphasize that its a big specialized thing they'll be downloading?

`Download raw SQLite database`
`Download entire SQLite database`

Or add a second link with guidance?

[Download the SQLite database](https://example.com) to [explore the data locally](https://github.com/cfpb/crawsqueal#how-to-query-the-crawler-database).

**Comment by csebianlander** [comment]
On board with `raw` since this is not a CSV or other familiar file format for non-dev users; also OK with the second link

**Comment by chosak** [comment]
Love the suggestion for the second link. Since this makes the link a little long it might fit better in the footer:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/654645/172404109-39cada3a-0501-4fa5-a220-daaf7e7fb6f4.png">

I'll open a PR with this change.
