### ISSUE TITLE
Viewer should allow for export of search results as CSV

### ISSUE THREAD

**Issue by chosak** [cfpb/crawsqueal#12]

**Comment by chosak** [comment]
Hi @huetingj @contolini do we have any good comps for this kind of "download a search result" pattern? The only one I could find is the CCDB search ([for example](https://www.consumerfinance.gov/data-research/consumer-complaints/search/?chartType=line&dateInterval=Month&dateRange=3y&date_received_max=2022-06-06&date_received_min=2019-06-06&lens=Overview&searchField=all&tab=Trends)) but this seems to be bespoke code for that page:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/654645/172231303-ecde4579-b3d2-422f-b641-4ee29561c14b.png">

Notably that "Export data" link isn't actually a download link (which is probably why it doesn't have the download icon), but pops up a separate dialog to customize the download, which we don't really need (yet) here.

That design looks okay to me, and I could implement via similarly bespoke code here, but if we have a standard pattern for this kind of thing it'd be nicer to use that.

**Comment by contolini** [comment]
I used to like how [hmda-explorer](https://github.com/cfpb/hmda-explorer) approximated the size of the file download for users so they wouldn't accidentally start downloading a massive file they didn't have time for. I can't find a screenshot but it was basically the same as the export link above with the filesize in parentheses.

So I'd vote for something like `Download results as a CSV file (approx. XX MB)` where the approximation can be a crude estimation created by multiplying X bytes by Y number of rows in the CSV.

**Comment by jenn-franklin** [comment]
Hi! Thanks for bringing attention to this. I don't think we have a standard format. I looked around and noticed CSV download offerings on charts within Data & Research vertical. Not the same situation but fyi:

On the [Origination activity page](https://www.consumerfinance.gov/data-research/consumer-credit-trends/credit-cards/origination-activity/)

![Screen Shot 2022-06-08 at 12 12 03 PM](https://user-images.githubusercontent.com/10562530/172666836-1bb31cd5-6e28-4cfc-b846-09959c7b30ec.png)

On the [Mortgages 90 or more days delinquent page](https://www.consumerfinance.gov/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/)

![Screen Shot 2022-06-08 at 12 12 55 PM](https://user-images.githubusercontent.com/10562530/172666862-d9e01f0f-5d60-46c9-93e6-b63429e1d5ca.png)

Maybe we arrive at something like this? (Just a note that I super quickly put this mockup together, so I'm totally open to up close feedback. And also I'll note that the underlines should be our traditional dotted style.)

![Screen Shot 2022-06-08 at 1 31 49 PM](https://user-images.githubusercontent.com/10562530/172680671-ac481f9d-3271-48f9-addc-02feda8aa557.png)

Thoughts: I went back and forth a bit on placement. In CCDB, on the one hand, I kind of like how the download/print links are zipped up succinctly in the results heading green bar. On the other hand, I kind of wish the results heading had its own, untouched space and that the download/print links sat tightly right below. Also, I will note that our standard link styling is not accessible on this green background. I see that in CCDB, the default link state has been modified to dark pacific, which is great and accessible. But the hover state is a much lighter tint of Pacific, which is not accessible. So, for this reason, I'm leaning toward pulling the download/print links out to sit below the green box and use our conventional link styling.

**Comment by jenn-franklin** [comment]
Seeing the above CSV placement idea implemented makes me feel like the link is getting lost. If not too much trouble, I'd like to flip my recommendation and have it sit within the green banner. So, like this:

![Screen Shot 2022-07-18 at 11 16 27 AM](https://user-images.githubusercontent.com/10562530/179544335-87652214-3855-4164-ad54-71f5b35bdc64.png)

Because Pacific isn't accessible on a green background, we'll need to change the link's default and focus states to be Mid Dark Pacific. The other links states can stay as is. 

@chosak @brandon-rusk
