### ISSUE TITLE
Does the crawler search for *all* component classes or just the first one?

### ISSUE THREAD

**Issue by contolini** [cfpb/crawsqueal#19]
When I search for `m-card__topic` it returns zero results but I know the homepage has topic cards.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1060248/173657780-80ba8a00-c9bf-4494-8618-f727c0678d05.png">

Is this happening because it's logging `m-card` and ignoring the subsequent `m-card__topic` class?

**Comment by chosak** [comment]
Unfortunately it does look like we only store the first class, confirming by looking in the database at what components we store for the homepage:

```
sqlite> select components from cfgov where path = '/';
["a-btn","a-link","a-overlay","a-tagline","a-text-input","m-btn-inside-input","m-card","m-global-banner","m-global-eyebrow","m-global-header-cta","m-global-search","m-hero","m-info-unit","m-list","m-notification","m-social-media","o-card-group","o-footer","o-footer-middle-left","o-footer-middle-right","o-footer-post","o-form","o-header","o-info-unit-group","o-mega-menu","o-well"]
```

The relevant code is in this [`getComponents`](https://github.com/cfpb/crawsqueal/blob/e8ab5b120317ba81fa6ab2b027ef9df9536f1d48/parser.js#L46-L69) function, which uses this regex: `/(?:(?:class=")|\s)((?:o|m|a)-[^_"__\s]*)/g`. According to https://regex101.com/r/iLlDG9/3 this works for `"m-card m-card-foo"` but not `"m-card m-card__topic"`, so something to do with the underscores.

If I change this to `/(?:(?:class=")|\s)((?:o|m|a)-[^"\s]*)/g`, this works better -- see https://regex101.com/r/LmkmUd/1.

PR opened at #22.
